import path from "path";
import { PUBLIC_ROOT_DIR } from "./path-constants";
import type { Cache } from "./get-cache";
import { mkdirAsync, writeFileAsync } from "../utils/fs";
import { putObject } from "../utils/cos";
import { cacheName } from "../utils/cacheName";

export async function setCache(data: Cache) {
  // 去重复数据
  const removedData = removeDuplicateContent(data);
  console.log(`[cache] Post-build cache generated by cli ${data.cliVersion}`);
  await putObject(removedData, cacheName());
}

// 去除多层数组中的重复数据，其中最里面的数组是个对象数组
export function removeDuplicateContent(data: Cache) {
  const { sources } = data;
  const result = sources.map((source) => {
    const { articles } = source;
    const obj: any = {};
    const result = articles.reduce((cur, next) => {
      obj[next.id] ? "" : (obj[next.id] = true && cur.push(next));
      return cur;
    }, []); // 转换成对象键值对的形式
    return {
      ...source,
      articles: result,
    };
  });
  return {
    ...data,
    sources: result,
  };
}
// 移除多余字段，并精简对应的RSS内容
